### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by vexleet**
## This PR contains those bug fixes
- bike is touching text in header
- margin between social buttons in header
- get directions on mobile
- a bit margin between sections
- Pin in map opens google map on click
- hover on read reveiws
- more padding for cookies
- address to be a link
- check file names

### CODE REVIEW

**Comment by PlamenMichev** [comment]
image
Should we make this distance on mobile smaller?

**Comment by PlamenMichev** [comment]
Also, the padding the sections could be extended even more imo, what do you think?

**Comment by vexleet** [comment]
> image Should we make this distance on mobile smaller?

Will look into it

**Comment by vexleet** [comment]
@PlamenMichev Resolved the comments, please check now. I didn't put much more margin between sections as I don't think big space is a good idea.

**Comment by PlamenMichev** [comment]
LGTM, push the json ld changes also pls

**Pull request merged**
